# Generated by Django 5.0.6 on 2024-05-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_numbers_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_code',
            field=models.CharField(default='76e5c8D7', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='numbers',
            name='number_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.URLField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='urls',
            name='url_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
