# Generated by Django 5.0.6 on 2024-05-27 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_personal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='urls',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_code',
            field=models.CharField(default='1a91FFd5', editable=False, max_length=8, unique=True),
        ),
    ]
