# Generated by Django 5.0.6 on 2024-05-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_numbers_user_id_alter_urls_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_code',
            field=models.CharField(default='EFFCBEbA', editable=False, max_length=8, unique=True),
        ),
    ]
