# Generated by Django 5.0.6 on 2024-05-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectfiles',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='user',
            new_name='user_id',
        ),
    ]
