# Generated by Django 5.0.6 on 2024-05-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_project_projectfiles_project_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfiles',
            name='video_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
