# Generated by Django 5.0.6 on 2024-05-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectfiles_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='file',
            field=models.FileField(blank=True, upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectfiles',
            name='video_url',
            field=models.URLField(blank=True),
        ),
    ]
